---
title: "RMarkdown Template"
author: "Author"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    toc_depth: 4
    keep_md: true
bibliography: references.bib
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
options(digits = 4, scipen = 2)
```



# Tidyposterior


see https://tidymodels.github.io/tidyposterior/articles/Getting_Started.html

<br><br>


```{r}
# devtools::install_github("tidymodels/tidyposterior")
library(tidyposterior)
library(ggplot2)
library(tidyverse)
theme_set(theme_bw())
```



```{r}
data("precise_example")

rocs <- precise_example %>%
   select(id, contains("ROC")) %>%
   setNames(tolower(gsub("_ROC$", "", names(.)))) 
rocs
```


```{r}
rocs_stacked <- tidyr::pivot_longer(rocs, cols = -id, names_to = "model", values_to = "statistic")

ggplot(rocs_stacked, aes(x = model, y = statistic, group = id, col = id)) + 
  geom_line(alpha = .75) + 
  theme(legend.position = "none")
```


```{r}
roc_model <- tidyposterior::perf_mod(rocs, seed = 2824)
roc_model$stan
```

```{r}
roc_post <- tidy(roc_model)
head(roc_post)
ggplot(roc_post) + 
  # Add the observed data to check for consistency 
  geom_point(
    data = rocs_stacked, 
    aes(x = model, y = statistic), 
    alpha = .5, col = "blue"
  )
```


# Contrast models

```{r}
glm_v_nnet <- contrast_models(roc_model, "nnet", "glm")
head(glm_v_nnet)
summary(glm_v_nnet, size = 0.02)
```

## THE ROPE

```{r}
ggplot(glm_v_nnet, size = 0.02)
```



```{r bib, include=FALSE}
# create a bib file for the R packages used in this document
knitr::write_bib(c('base', 'rmarkdown'), file = 'skeleton.bib')
```


<br> <br>

# Session Info

```{r}
devtools::session_info()
```

<br> <br>

# References
